[phases.install]
cmds = [
  "cd client && npm ci --include=dev",
  "cd server && npm ci --include=dev"
]

[phases.build]
cmds = [
  "cd client && npm run build",
  "cd server && npx prisma generate --schema=src/prisma/schema.prisma",
  "cd server && npm run build"
]
